stages:
  train_v1:
    cmd: python train_with_mlflow.py --params params_v1.yaml
    deps:
      - train_with_mlflow.py
      - data/vehicle_data_v1
    outs:
      - ./app/core/models/vehicle_detection/exp_v1

  train_v2:
    cmd: python train_with_mlflow.py --params params_v2.yaml
    deps:
      - train_with_mlflow.py
      - data/vehicle_data_v2
    outs:
      - ./app/core/models/vehicle_detection/exp_v2

  train_v3:
    cmd: python train_with_mlflow.py --params params_v3.yaml
    deps:
      - train_with_mlflow.py
      - data/vehicle_data_v3
    outs:
      - ./app/core/models/vehicle_detection/exp_v3

  monitor:
    cmd: python monitor/monitor_drift.py #--feedback-dir feedback/
    deps:
      - monitor/monitor_drift.py
      - feedback/
    outs:
      - monitor/drift_report.json

  retrain:
    cmd: bash scripts/retrain.sh
    deps:
      - scripts/retrain.sh
      - feedback/
      - data/vehicle_data_v1
    outs:
      - ./app/core/models/vehicle_detection/exp_v4
